name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add secrets
        run: |
          echo "${{ secrets.TEST_ENV_FILE }}" > .test.env

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Verify dependencies
        run: go mod verify

      - name: Install dependencies
        run: go mod download

      - name: Install atlas
        run: curl -sSf https://atlasgo.sh | sh

      - name: Run migrations
        run: atlas migrate apply --env prod -u "postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable" --revisions-schema public

      - name: Seed database
        run: go run cmd/seed/main.go

      - name: Run tests
        run: go test ./internal/handlers -v
